### ISSUE TITLE
[GOOD_PRACTICES] Front end error handling

### ISSUE THREAD

**Issue by hazzo** [mrmilu/engineering_proposals#4]
### What problem are you trying to solve?
* Every new front end application, either web or mobile, handles and treats errors differently. We should have an unified way of detecting and classifying error and producing side effects in the UI.

### Why should we solve it?
* It's inefficient and time consuming to rethink how to handle errors in a front end application, there should be a standard.
* A standard will guarantee that minimum cases are covered.
* An unified way tested accross several applications can give us robustness.

### How do you propose to solve it?
* Contract proposal in this repository of which errors should we detect and how we can handle them
* Implementation in react_base, next_base and flutter_base projects.

### What could go wrong?
* We could be either too general on error catching or too specific. We should be in a middle ground and let specific projects and use cases the ability to extend this error handling.

### Tasks
* _Future tasks that will be listed once discussion starts on thread issue_
- [ ] Contract proposal
- [ ] react_base implementation
- [ ] next_base implementation
- [ ] flutter_base implementation

**Comment by jherencia** [comment]
Looks good to me :)

**Comment by hazzo** [comment]
> Looks good to me :)

Already started proposal on a branch, as soon as I have a draft I'll hit you with a PR
